DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    id IDENTITY NOT NULL PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname  VARCHAR(50) NOT NULL,
    username  VARCHAR(50) NOT NULL,
    password  VARCHAR(50) NOT NULL
);